### ISSUE TITLE
Server erstes Lesen

### ISSUE THREAD

**Issue by FenjaSchulz** [Steffen911/WIProjekt#1]
GameSceneController ab Zeile 58 (Methode playGame) spielt.
ToDos: 
1. Stimmt die ServerKommunikation so - Bitte ggf. in ServerGUIKommunkation ändern
2. Wie läuft das beim 1. Empfangen, ist reader da eine andere Methode?!

**Comment by Steffen911** [comment]
ServerGuiKontakt ist mMn nicht nötig. Das geht alles über die existierenden Klassen

Beim ersten Empfangen ist reader nur die Lesemethode. communicate schreibt und wartet auf Antwort

**Comment by ghost** [comment]
Ist das Ganze denn asynchron?

**Comment by Steffen911** [comment]
Wieso sollte es denn asynchron sein?
Und ja, ist es...
